// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA33lHWWCwNO2ReP1my_EEeu5kNd9b1xuU',
    appId: '1:945647869344:android:0a81e4ed4843d3125b98c5',
    messagingSenderId: '945647869344',
    projectId: 'wio-care',
    storageBucket: 'wio-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlcg4SHQdWyKwBsKN8FRC_834aZVLCoUA',
    appId: '1:945647869344:ios:220dedc16666788a5b98c5',
    messagingSenderId: '945647869344',
    projectId: 'wio-care',
    storageBucket: 'wio-care.firebasestorage.app',
    androidClientId: '945647869344-5kjir07a1cg361cfmktreiu70f79d3jl.apps.googleusercontent.com',
    iosClientId: '945647869344-0pdmf69co021irnd165v8cojj8hi36tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.wioDoctor',
  );
}
